// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Robot.h"
#include <vector>
#include <algorithm>

#include <Autonomous/Steps/DriveSteps.h>

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZATION
std::shared_ptr<DriveBase> Robot::driveBase;
std::shared_ptr<GearSystem> Robot::gearSystem;
std::shared_ptr<ClimberSystem> Robot::climberSystem;
std::shared_ptr<ShooterSystem> Robot::shooterSystem;
std::shared_ptr<BallPickupSystem> Robot::ballPickupSystem;
std::unique_ptr<OI> Robot::oi;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZATION

void Robot::RobotInit() {
	RobotMap::init();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    driveBase.reset(new DriveBase());
    gearSystem.reset(new GearSystem());
    climberSystem.reset(new ClimberSystem());
    shooterSystem.reset(new ShooterSystem());
    ballPickupSystem.reset(new BallPickupSystem());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	// This MUST be here. If the OI creates Commands (which it very likely
	// will), constructing it during the construction of CommandBase (from
	// which commands extend), subsystems are not guaranteed to be
	// yet. Thus, their requires() statements may grab null pointers. Bad
	// news. Don't move it.
	oi.reset(new OI());

	// instantiate the command used for the autonomous period
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
	autonomousCommand.reset(new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
	managers.push_back(gearSystem);
	managers.push_back(climberSystem);
	managers.push_back(shooterSystem);
	managers.push_back(ballPickupSystem);

	world.reset(new World());
	autoManager.reset(new AutoManager());


	// driveBase Twist control
	// TODO: Think about better place than this
	Preferences *prefs = Preferences::GetInstance();
	if (!prefs->ContainsKey("TwistP")) {
		prefs->PutFloat("TwistP", 0.02);
	}
	if (!prefs->ContainsKey("TwistI")) {
		prefs->PutFloat("TwistI", 0.0);
	}
	if (!prefs->ContainsKey("TwistD")) {
		prefs->PutFloat("TwistD", 0.12);
	}
	// driveBase Twist Control

	// driveBase Drive PID Control
	if (!prefs->ContainsKey("DriveP")) {
		prefs->PutFloat("DriveP", 2);
	}
	if (!prefs->ContainsKey("DriveI")) {
		prefs->PutFloat("DriveI", 0.001);
	}
	if (!prefs->ContainsKey("DriveD")) {
		prefs->PutFloat("DriveD", 0.0);
	}
	if (!prefs->ContainsKey("DriveF")) {
		prefs->PutFloat("DriveF", 3.93);
	}
	if (!prefs->ContainsKey("DriveIZone")) {
		prefs->PutFloat("DriveIZone", 20.0);
	}
	// driveBase Drive PID
	if (!prefs->ContainsKey("DriveControlP")) {
		prefs->PutFloat("DriveControlP", 0.001);
	}
	if (!prefs->ContainsKey("DriveControlI")) {
		prefs->PutFloat("DriveControlI", 0.0);
	}
	if (!prefs->ContainsKey("DriveControlD")) {
		prefs->PutFloat("DriveControlD", 0.0);
	}
	if (!prefs->ContainsKey("DriveControlF")) {
		prefs->PutFloat("DriveControlF", 0);
	}
	if (!prefs->ContainsKey("DriveControlIZone")) {
		prefs->PutFloat("DriveControlIZone", 0.0);
	}

	// Autonomous
	if (!prefs->ContainsKey(DriveUnit::PULSES_PER_INCH)) {
		prefs->PutDouble(DriveUnit::PULSES_PER_INCH, 16.5);
	}
	// TODO: Store boiler right X/Y coordinates
	if (!prefs->ContainsKey("RightGearX")) {
		prefs->PutDouble("RightGearX", -83);
	}
	if (!prefs->ContainsKey("RightGearY")) {
		prefs->PutDouble("RightGearY", 96);
	}
	if (!prefs->ContainsKey("RightGearT")) {
		prefs->PutDouble("RightGearT", 1.5);
	}

  }

/**
 * This function is called when the disabled button is hit.
 * You can use it to reset subsystems before shutting down.
 */
void Robot::DisabledInit(){

}

void Robot::DisabledPeriodic() {
	Scheduler::GetInstance()->Run();
	RunManagerSMDBs();
	frc::SmartDashboard::PutNumber("Gyro Angle", RobotMap::gyro->GetAHRS()->GetAngle());
}

void Robot::AutonomousInit() {
	if (autonomousCommand.get() != nullptr) {
		autonomousCommand->Start();
	}
	world.reset(new World());
	world->Init();
	autoManager->Init(world);
	InitManagers();
}

void Robot::AutonomousPeriodic() {
	// Update World
	Scheduler::GetInstance()->Run();
	autoManager->Periodic(world);
	RunManagers();
}

void Robot::TeleopInit() {
	// This makes sure that the autonomous stops running when
	// teleop starts running. If you want the autonomous to
	// continue until interrupted by another command, remove
	// these lines or comment it out.
	if (autonomousCommand.get() != nullptr) {
		autonomousCommand->Cancel();
	}
	driveBase->InitTeleop();
	InitManagers();
}

void Robot::TeleopPeriodic() {
	Scheduler::GetInstance()->Run();
	bool useCrab = true;
	bool useDriveBaseAngle = false;
	bool robotCentricCrab = false;
	bool firing = false;

	if (oi->DR1->Pressed()) {
		shooterSystem->SetFireEnabled(true);
		firing = true;
	} else {
		shooterSystem->SetFireEnabled(false);
	}

	if (oi->DR2->RisingEdge()) {
		gearSystem->EjectGear();
	}

	if (oi->DL1->Pressed()) {
		useCrab = false;
	}


	if (oi->DL2->Pressed()) {
		// Only run auto-centering when we are in field-centric crabbing
		if (useCrab) {
			driveBase->SetTargetAngle(0.0);
			useDriveBaseAngle = true;
		} else {
			robotCentricCrab = true;
		}
	}

	if (oi->DL4->Pressed()) {
		driveBase->SetTargetAngle(60.0);
		useDriveBaseAngle = true;
	}

	if (oi->DL5->Pressed()) {
		driveBase->SetTargetAngle(-60.0);
		useDriveBaseAngle = true;
	}



	if (oi->GPStart->RisingEdge()) {
		ballPickupSystem->ToggleBallPickup();
	}
	if (oi->GPBack->RisingEdge()) {
		ballPickupSystem->ReverseBallPickup();
	}

	if (oi->GPX->RisingEdge()) {
		shooterSystem->ToggleShooter();
	}

	if (oi->GPY->RisingEdge()) {
		gearSystem->ResetGear();
	}
	if (oi->GPB->RisingEdge()) {
		gearSystem->EjectGear();
	}
	if (oi->GPA->RisingEdge()) {
		gearSystem->PickUpGear();
	}

	if (oi->GPLB->RisingEdge()) {
		climberSystem->ToggleProd();
	}

	if (oi->GPRB->RisingEdge()) {
		gearSystem->ToggleGearBarReverse();
	}


	climberSystem->SetClimberSpeed(oi->GetGamepadLT());
	gearSystem->SetGearBarSpeed(oi->GetGamepadLeftStick());
	shooterSystem->SetHopperSpeed(oi->GetGamepadRightStick());


	const double threshold = (firing) ? 0.2 : 0.1;
	bool lockWheels = false;
	if (firing) {
		if (fabs(oi->GetJoystickTwist(threshold)) > 0 ||
			fabs(oi->GetJoystickX(threshold)) > 0 ||
			fabs(oi->GetJoystickY(threshold)) > 0) {
			lockWheels = false;
		} else {
			lockWheels = true;
		}
	}

	if (useCrab || robotCentricCrab) {
		const double twistInput = (useDriveBaseAngle) ?
					driveBase->GetTwistControlOutput() :
					oi->GetJoystickTwist(threshold);
		const bool useGyro = !robotCentricCrab;

		if (!lockWheels) {
			driveBase->Crab(
					twistInput,
					-oi->GetJoystickY(threshold),
					oi->GetJoystickX(threshold),
					useGyro);
		} else {
			driveBase->Lock();
		}
	} else {
		// Ackermann Steering
		driveBase->Steer(oi->getLeftJoystickXRadians(),
						 oi->GetJoystickY(),
						 0.5);
	}

	SmartDashboard::PutNumber("GyroAngle",RobotMap::gyro->GetYaw());

	RunManagers();
}

void Robot::TestPeriodic() {
	lw->Run();
}


void Robot::InitManagers() {
	const Manager::RunMode runMode = (IsAutonomous() ? Manager::RunMode::kAuto : Manager::RunMode::kTele);
	std::for_each(managers.begin(), managers.end(),
			[=](std::shared_ptr<Manager> &manager) {
				manager->InitManager(runMode);
			});
}

void Robot::RunManagers() {
	std::for_each(managers.begin(), managers.end(),
			[](std::shared_ptr<Manager> &manager) {
				manager->Run();
				manager->SMDB();
			});
	autoManager->SMDB();
}

void Robot::RunManagerSMDBs() {
	std::for_each(managers.begin(), managers.end(),
			[](std::shared_ptr<Manager> &manager) {
				manager->SMDB();
			});
	autoManager->SMDB();
}

START_ROBOT_CLASS(Robot);

