// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef GEARSYSTEM_H
#define GEARSYSTEM_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "Manager.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class GearSystem: public Subsystem, public Manager {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<CANTalon> gearPickUp;
	std::shared_ptr<Solenoid> lift;
	std::shared_ptr<Solenoid> rotate;
	std::shared_ptr<Solenoid> extend;
	std::shared_ptr<DoubleSolenoid> squeeze;
	std::shared_ptr<Compressor> gearCompressor;
	std::shared_ptr<AnalogInput> pressureGauge;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	GearSystem();
	void InitDefaultCommand();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	void Run();
	void SMDB();
	void SetGearBarSpeed(double speed);

	void ToggleLift();
	void ToggleRotate();
	void ToggleExtend();
	void ToggleSqueeze();

};

#endif
